apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-deployment
spec:
  replicas: 1 # amount of pods
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice # - symbol in yaml means it's an array
          image: jvarsl/platformservice:latest
# commands:
# kubectl version --short
# kubectl apply -f platforms-deploy.yaml
# kubectl get deployments
# kubectl get pods
