apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-svr
spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 80
      targetPort: 80

# kubectl apply -f platforms-nodeport-service.yaml
# to get port of node port (in ports column): kubectl get services